### ISSUE TITLE
How To: For best results, set your text size to 'Tiny'

### ISSUE THREAD

**Issue by Grossdm** [siyangqiu/FFTextWrap#1]
On **AMO**, you write:
> For best results, set your text size to 'Tiny'

Since this addon is for Fennec, I hope that you are aware that Mozilla decided that users should not be able to select a text size. 😞 

The _only_ option close to this is under Accessibility: `Use system font size`. 😠 

I certainly hope that you are not implying that users should change this setting in Accessibility, **and** that users change the font size for their _entire system!_ 😲 

Please explain what you mean with this statement.

**Comment by siyangqiu** [comment]
I was not aware that they have removed the font size slider that used to be there. Thanks! I've removed the text from the description.

**Comment by Grossdm** [comment]
Thank you for your response!

I wonder whether the `Use system font size` option should be on or off.

Perhaps you could test this to give advice to users?

Doug®

**Comment by siyangqiu** [comment]
I'd put it as off. It is basically the same as the font size slider from before, but it uses your system font size. The default font size actually looks good (I previously thought I changed it), so using it may just make things look weird if you have a larger system font size.
